### ISSUE TITLE
Handle ConnectionError better/support retries

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/api-utils-python#35]
We received a ConnectionError stack trace that involved this library. It seems like this should support retries and also handle this error in the _api_call method. 

```
Traceback (most recent call last):
  File "run_jobs.py", line 127, in <module>
    manager.run_jobs()
  File "run_jobs.py", line 93, in run_jobs
    job.run()
  File "run_jobs.py", line 65, in run
    self.data_sources = start_method()
  File "/app/course_inventory/inventory.py", line 254, in run_course_inventory
    course_df = gather_course_data_from_api(ACCOUNT_ID, TERM_IDS)
  File "/app/course_inventory/inventory.py", line 161, in gather_course_data_from_api
    response = make_request_using_api_utils(url_ending_with_scope, next_params)
  File "/app/course_inventory/inventory.py", line 58, in make_request_using_api_utils
    response = API_UTIL.api_call(url, SUBSCRIPTION_NAME, payload=request_params)
  File "/usr/local/lib/python3.8/site-packages/autologging.py", line 916, in autologging_traced_instancemethod_delegator
    return method(*args, **keywords)
  File "/src/umich-api/umich_api/api_utils.py", line 95, in api_call
    return this_scope.get("api_call")(api_call, self.get_access_token(this_scope.get("token_url"), client_scope), method, payload)
  File "/usr/local/lib/python3.8/site-packages/ratelimit/decorators.py", line 113, in wrapper
    return func(*args, **kargs)
  File "/usr/local/lib/python3.8/site-packages/ratelimit/decorators.py", line 80, in wrapper
    return func(*args, **kargs)
  File "/usr/local/lib/python3.8/site-packages/autologging.py", line 916, in autologging_traced_instancemethod_delegator
    return method(*args, **keywords)
  File "/src/umich-api/umich_api/api_utils.py", line 115, in _api_call
    resp = requests.get(api_url, headers=headers, params=payload)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
```

**Comment by jonespm** [comment]
This may want to use the back off library.
https://pypi.org/project/backoff/

**Comment by ssciolla** [comment]
@jonespm, I think the approach in that SO article, using `urllib3`, looks really promising. I'm not as familiar with using `requests.Session`. Is this something we can transition to easily in this library?

**Comment by ssciolla** [comment]
Actually, @jonespm, it looks `Session` would also offer some other advantages in terms of code simplification: https://docs.python-requests.org/en/master/user/advanced/

I can start trying a refactor, when I have a little free time 😭

**Comment by jonespm** [comment]
From what I can see with urllib3 is that it does retry by default 3 times before throwing this MaxRetryError. So there **are** some retries going on here.

https://urllib3.readthedocs.io/en/stable/user-guide.html#retrying-requests

**Comment by ssciolla** [comment]
@jonespm, are you sure? I'm looking at the `HTTPAdapter`, where `requests` links to `urllib3`, and it doesn't look anything is happening by default? https://2.python-requests.org/en/master/api/#requests.adapters.HTTPAdapter
